# Generated by Django 4.0.4 on 2022-06-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(default='null', upload_to='frontend/static/images/courseImage')),
                ('course_banner', models.ImageField(default='null', upload_to='frontend/static/images/courseBanner')),
                ('presentationVideo', models.FileField(default='null', upload_to='frontend/static/images/courseVideo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('video', models.FileField(default='null', upload_to='frontend/static/video/courseLesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.course')),
            ],
        ),
    ]
