# Generated by Django 4.0.4 on 2022-06-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='image',
            field=models.ImageField(default='null', upload_to='frontend/static/images/courseThumbnail'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='cursos.course'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
