# Generated by Django 4.0.4 on 2022-06-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_courseposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseposts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseposts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
