# Generated by Django 4.0.4 on 2022-06-14 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_courseposts_date_alter_courseposts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseposts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
