# Generated by Django 4.0.4 on 2022-06-14 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_courseposts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseposts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
