# Generated by Django 4.0.3 on 2022-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('tempo', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('descricao', models.CharField(max_length=260)),
                ('conteudo', models.CharField(max_length=260)),
            ],
        ),
    ]
