# Generated by Django 4.0.4 on 2022-06-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='presentationVideo',
            field=models.FileField(default='null', upload_to='../frontend/static/courses/'),
        ),
    ]
