# Generated by Django 4.0.4 on 2022-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_presentationvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='null', upload_to='./static/courses/coursesImages/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='course',
            name='presentationVideo',
            field=models.FileField(default='null', upload_to='./static/courses/<django.db.models.fields.CharField>'),
        ),
    ]
